### ISSUE TITLE
how to build a mine that's not biotestmine?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/docker-intermine-gradle#2]
We talked about this already a bit.

Example:

1. I want to make `tigerMine`.
2. I run [make_mine](https://github.com/intermine/intermine-scripts/blob/master/make_mine) to generate a new InterMine. This script creates `~/git/tigermine`
3. I update project XML to have a single source:

```
    <source name="go" type="go">
      <property name="src.data.file" location="/data/go-annotation/go-basic.obo"/>
    </source>
```
4. I download the file [go-basic.obo](http://geneontology.org/docs/download-ontology/) and place it in `/data/go-annotation/`

How can I then use the docker files to build my tigerMine?

**Comment by leoank** [comment]
I am updating the docs and build script to support this use case.

**Comment by leoank** [comment]
let me know if this worked for you.

**Comment by leoank** [comment]
Updated the docs with working instructions. Reopen this issue if you still face problems.
