### ISSUE TITLE
optimise postgres config

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/docker-intermine-gradle#4]
```
intermine_postgres   | LOG:  checkpoints are occurring too frequently (4 seconds apart)
intermine_postgres   | HINT:  Consider increasing the configuration parameter "checkpoint_segments".
```

https://intermine.readthedocs.io/en/latest/system-requirements/software/postgres/postgres/#postgresql-parameters

We recommend this setting:

```
checkpoint_segments | 128
```

Is there an easy way to update the config of the postgres in the docker container?

**Comment by leoank** [comment]
you can easily do this! look for `postgresql.conf` file inside postgres directory. Modify it according to your needs. Only caveat is that you cannot use prebuilt  images. You have to use Option 1 in the quickstart section to build images locally.
