### ISSUE TITLE
Duplication in user docs?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/docker-intermine-gradle#6]
Is this:

https://github.com/intermine/docker-intermine-gradle/blob/master/README.md#change-default-settings-optional

Doing the same thing as this:

https://github.com/intermine/docker-intermine-gradle/blob/master/README.md#set-environment-variables

Maybe we could delete that last section? Or are they setting the ENV variables locally and for docker so we need both?

**Comment by leoank** [comment]
Sorry for ignoring this issue for so long! README looks good now.
